#!/bin/bash
items=("Tint" "Xp" "Cava" "Xplr" "Web Download (via curl)")
choice=$(printf "%s\n" "${items[@]}" | fzf-tmux -p --prompt="Programs  " --height=~50% --layout=reverse --border --exit-0)
if [[ -z $choice ]]; then
	echo "Nothing selected"
	exit 1
fi
case $choice in
	"Tint")
		tint -n;;
	"Xp")
		xp;;
	"Cava")
		cava;;
	"Xplr")
		xplr;;
	"Web Download (via curl)")
		read -p "Insert link here  " dwlink
		curl -fLO $dwlink;;
	*)
		echo "how";;
esac

